name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install dependencies
        working-directory: lp_app
        run: composer install

      - name: Set up application key
        working-directory: lp_app
        run: php artisan key:generate

      - name: Create SQLite database
        working-directory: lp_app
        run: |
          touch database/database.sqlite
          php artisan migrate --seed --force

      - name: Install Chromedriver for Dusk
        working-directory: lp_app
        run: php artisan dusk:chrome-driver

      - name: Run tests
        working-directory: lp_app
        run: php artisan test

  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Run Docker container
        run: |
          docker run -d --name myapp-container -p 8000:8000 myapp:latest
          sleep 10 # Attendre que le conteneur démarre

      - name: Run tests inside Docker
        run: |
          docker exec myapp-container php artisan test