name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
          MYSQL_DATABASE: todo_app
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install dependencies
      working-directory: ./lp_app
      run: composer install --no-interaction --prefer-dist

    - name: Set up .env
      working-directory: ./lp_app
      run: cp .env.example .env

    - name: Run migrations
      working-directory: ./lp_app
      run: php artisan migrate --database=mysql

    - name: Run tests
      working-directory: ./lp_app
      run: php artisan test --env=testing
